### ISSUE TITLE
A test fails on Mac running 

### ISSUE THREAD

**Issue by arunavam** [octapps/octapps#22]
The following test fails on my MacbookPro 15-inch (2016, touch-bar edition) running "MacOS Sierra 10.12.6": 

amplitudeParams2Vect.m                          : TEST(S) FAILED
amplitudeParams2Vect.m: ------------------------------------------------
amplitudeParams2Vect.m: ***** test
amplitudeParams2Vect.m:   p0 = struct("h0", 1e-24, "cosi", 0, "psi", pi/4, "phi0", pi/5);
amplitudeParams2Vect.m:   p = amplitudeVect2Params(amplitudeParams2Vect(p0));
amplitudeParams2Vect.m:   assert(p.h0, p0.h0, 1e-3);
amplitudeParams2Vect.m:   assert(p.cosi, p0.cosi, 1e-3);
amplitudeParams2Vect.m:   assert(p.psi, p0.psi, 1e-3);
amplitudeParams2Vect.m:   assert(p.phi0, p0.phi0, 1e-3);
amplitudeParams2Vect.m: !!!!! test failed
amplitudeParams2Vect.m: ASSERT errors for:  assert (p.psi,p0.psi,1e-3)
amplitudeParams2Vect.m:
amplitudeParams2Vect.m:   Location  |  Observed  |  Expected  |  Reason
amplitudeParams2Vect.m:      ()        -0.7854       0.7854      Abs err 1.5708 exceeds tol 0.001
amplitudeParams2Vect.m: ------------------------------------------------
make[1]: *** [/var/folders/73/c9w9hv2n3tj4fth543hn6gp00000gn/T/octapps-make-check.XXXXXX.aW7Dx8H0/amplitudeParams2Vect.m.test] Error 1
make[1]: *** Deleting file `/var/folders/73/c9w9hv2n3tj4fth543hn6gp00000gn/T/octapps-make-check.XXXXXX.aW7Dx8H0/amplitudeParams2Vect.m.test'
make: *** [check] Error 1

**Comment by kwwette** [comment]
I believe this is fixed now.
