### ISSUE TITLE
Hey guys, any idea about the failing tests?

### ISSUE THREAD

**Issue by ReinhardPrix** [octapps/octapps#48]
- seems they are consistently broken now, any idea what's going on?

/cc @kwwette @dbkeitel

**Comment by kwwette** [comment]
Haven't looked at these in a long time. Looks like some of the `CostFunctions*` tests are coverging to different reference results, hence the failures. Not sure why though.

**Comment by ReinhardPrix** [comment]
Hi Karl, yes, indeed, I did a few spot checks and it seems the 'new' solutions are worse than the original ones though (L0 < L0_orig). These changes seem to have been caused by the rounding of Nseg and ndim and the removal of stepsize contraction. The other failure stems from missing at-least dummy test in CostFunctionsWeave ...

**Comment by kwwette** [comment]
Ah okay, I'd hoped those changes wouldn't have broken anything, but must not have checked carefully. Feel free to revert them if they've broken the tests.

**Comment by ReinhardPrix** [comment]
closed by #49
